import { v4 as uuidv4 } from "uuid";
function chillHop() {
  return [
    {
      name: "Adorable",
      cover: process.env.PUBLIC_URL + "/adorable.jpg",
      artist: "Jahy-Sama",
      audio: process.env.PUBLIC_URL + "/jahy-sama-adorable.mp3",
      color: ["#4f73fb", "#682c8c"],
      id: uuidv4(),
      active: true,
      favorite: true,
    },
    {
      name: "Alone",
      cover: process.env.PUBLIC_URL + "/alone.jpg",
      artist: "Alan Walker & Ava Max",
      audio:
        process.env.PUBLIC_URL +
        "/nightcore-alone-pt-ii-alan-walker-ava-max-lyrics.mp3",
      color: ["#205950", "#2ab3bf"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "Butterflies",
      cover: process.env.PUBLIC_URL + "/butterflies.jpg",
      artist: "Zendaya",
      audio: process.env.PUBLIC_URL + "/nightcore-butterflies.mp3",
      color: ["#f8f2fa", "#aa9ebe"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "Do Me",
      cover: process.env.PUBLIC_URL + "/do-me.jpg",
      artist: "Kim Petras",
      audio: process.env.PUBLIC_URL + "/nightcore-do-me.mp3",
      color: ["#d992b4", "#502f4c"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "Everytime we touch",
      cover: process.env.PUBLIC_URL + "/everytime-we-touch.jpg",
      artist: "Cascada",
      audio: process.env.PUBLIC_URL + "/nightcore-everytime-we-touch-remix.mp3",
      color: ["#fa985b", "#aa3931"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "How do you do",
      cover: process.env.PUBLIC_URL + "/how-do-you-do.jpg",
      artist: "Boom",
      audio: process.env.PUBLIC_URL + "/nightcore-how-do-you-do-remix.mp3",
      color: ["#92849d", "#41455e"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "I Scare Myself",
      cover: process.env.PUBLIC_URL + "/i-scare-myself.jpg",
      artist: "Beth Crowley",
      audio:
        process.env.PUBLIC_URL +
        "/nightcore-i-scare-myself-beth-crowleylyrics.mp3",
      color: ["#c34225", "#a60c0a"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "Let It Die",
      cover: process.env.PUBLIC_URL + "/let-it-die.jpg",
      artist: "Rival",
      audio: process.env.PUBLIC_URL + "/nightcore-let-it-die-lyrics.mp3",
      color: ["#504f54", "#0d1313"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "Live A Lie",
      cover: process.env.PUBLIC_URL + "/live-a-lie.jpg",
      artist: "Rival x Egzod (ft. Andreas Stone)",
      audio: process.env.PUBLIC_URL + "/nightcore-live-a-lie-lyrics.mp3",
      color: ["#b3c7df", "#5f648a"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "Lost In Japan",
      cover: process.env.PUBLIC_URL + "/lost-in-japan.jpg",
      artist: "Shawn Mendes",
      audio: process.env.PUBLIC_URL + "/nightcore-lost-in-japan.mp3",
      color: ["#edc9a5", "#9e2e54"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "Love Like Mine",
      cover: process.env.PUBLIC_URL + "/love-like-mine-2.jpg",
      artist: "Stela Cole",
      audio:
        process.env.PUBLIC_URL +
        "/nightcore-love-like-mine-lyrics-stela-cole.mp3",
      color: ["#fb9ed5", "#d13f8a"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "Mad At Disney",
      cover: process.env.PUBLIC_URL + "/mad-at-disney.jpg",
      artist: "Avocuddle",
      audio: process.env.PUBLIC_URL + "/nightcore-mad-at-disney-lyrics.mp3",
      color: ["#76899a", "#2c3532"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "Naughty Naughty",
      cover: process.env.PUBLIC_URL + "/naughty-naughty.jpg",
      artist: "Porcelain Black",
      audio: process.env.PUBLIC_URL + "/nightcore-naughty-naughty-lyrics.mp3",
      color: ["#d7c4c6", "#a4264c"],
      id: uuidv4(),
      active: false,
      favorite: false,
    },
    {
      name: "No Friends",
      artist: "Cadmium (ft. Rosendale)",
      cover: process.env.PUBLIC_URL + "/no-friends.jpg",
      id: uuidv4(),
      active: false,
      favorite: false,
      color: ["#f1bd6a", "#b35242"],
      audio: process.env.PUBLIC_URL + "/nightcore-no-friends-lyrics.mp3",
    },
    {
      name: "Oops, I Did It Again",
      artist: "Why Mona (Unlike Pluto x Joanna Jones",
      cover: process.env.PUBLIC_URL + "/oups-i-did-it-again.jpg",
      id: uuidv4(),
      active: false,
      favorite: false,
      color: ["#c14194", "#3b3e47"],
      audio: process.env.PUBLIC_URL + "/nightcore-oops-i-did-it-again-nv.mp3",
    },
    {
      name: "People I Don't Like",
      artist: "Upsahl",
      cover: process.env.PUBLIC_URL + "/people-i-dont-like.jpg",
      id: uuidv4(),
      active: false,
      favorite: false,
      color: ["#cc747b", "#6d4d47"],
      audio:
        process.env.PUBLIC_URL + "/nightcore-people-i-dont-like-upsahl.mp3",
    },
    {
      name: "Play Date",
      artist: "Melanie Martinez",
      cover: process.env.PUBLIC_URL + "/play-date.jpg",
      id: uuidv4(),
      active: false,
      favorite: false,
      color: ["#fc7c3d", "#da2e20"],
      audio: process.env.PUBLIC_URL + "/nightcore-play-date-lyrics.mp3",
    },
    {
      name: "Pretty Girl",
      artist: "Maggie Lindemann",
      cover: process.env.PUBLIC_URL + "/pretty-girl.jpg",
      id: uuidv4(),
      active: false,
      favorite: false,
      color: ["#edc1b4", "#995f5d"],
      audio: process.env.PUBLIC_URL + "/nightcore-pretty-girl.mp3",
    },
    {
      name: "Rumors",
      artist: "Neffex",
      cover: process.env.PUBLIC_URL + "/rumors.jpg",
      id: uuidv4(),
      active: false,
      favorite: false,
      color: ["#aa9ef0", "#62ee51"],
      audio: process.env.PUBLIC_URL + "/nightcore-neffex-rumors-lyrics.mp3",
    },
    {
      name: "Who's Laughing Now?",
      artist: "Ava Max",
      cover: process.env.PUBLIC_URL + "/whos-laughing-now.jpg",
      id: uuidv4(),
      active: false,
      favorite: false,
      color: ["#e1c8b4", "#7951c3"],
      audio: process.env.PUBLIC_URL + "/nightcore-whos-laughing-now.mp3",
    },
    {
      name: "Wrap Me In Plastic",
      artist: "Chromance",
      cover: process.env.PUBLIC_URL + "/wrap-me-in-plastic.jpg",
      id: uuidv4(),
      active: false,
      favorite: false,
      color: ["#b86a94", "#b04e81"],
      audio:
        process.env.PUBLIC_URL + "/nightcore-wrap-me-in-plastic-lyrics.mp3",
    },
  ];
}

export default chillHop;
